### ISSUE TITLE
Support for receiving/replying to messages?

### ISSUE THREAD

**Issue by ghost** [michael-lazar/rtv#109]
Does the PRAW api support messages/inbox/etc? If so, would it be possible to implement a little notification when you have unread messages, a command to go to the inbox, reply to messages, things like that?

This is the only feature that keeps me opening reddit in a browser at this point.

I'd be happy to start working on this if it's something you think is feasible.

**Comment by Brobin** [comment]
I'm fairly certain this is supported by praw. This would be great! Maybe it
could be added to the `/me` page.

**Comment by mekhami** [comment]
What I was thinking was, when you use Reddit in the browser each request carries with it a notification if you have an unread message, so I assume that's part of the API. I'd like to be browsing normally in rtv and have a notification if I've received an inboxed message/comment/reply etc. 

So each call to PRAW would have to contain this notification. If it does, simple! If not, do we want some sort of timer that will hit the API and check for messages? How much can we do within each request to check for an inboxed item?

**Comment by michael-lazar** [comment]
It's possible to check for unread messages with PRAW, but I don't believe that Reddit's API supports sending the notification with each request. You have to check for notifications explicitly (see [get_unread()](https://praw.readthedocs.org/en/v2.1.21/pages/code_overview.html#praw.__init__.PrivateMessagesMixin.get_unread)). The two approaches that you could take would be:

1. Implement a timer as you suggested. Have it make a new request every 30 seconds or so.
2. Check for messages every time the user switches to a new page or refreshes the screen.
3. Some hybrid of 1 and 2, where every time the user opens a new page it checks how much time has elapsed.

I would advise against option 1 because it will involve spinning off threads that need to interact with the main program loop. This would be a huge pain to implement. Option 2 could work, the main issue is that each PRAW request takes 2 seconds, and you don't want to block the user from doing anything for an additional 2 seconds every time they load a page. You might have to get creative here.

I think this is a cool idea. My suggestion would be to keep it simple at first and focus on just the notification. That in and of itself is worth adding. Once that is done, we can worry about viewing the inbox and replying to messages and such.

**Comment by mekhami** [comment]
I wonder if you could fire off the two requests, one for get_unread() and
one for whatever the user was requesting, simultaneously. i would really
want the get_unread() call to be non blocking, or i don't think it would be
worth doing.

i'll do some research and get back to you on this. in the meantime if you
have implementation ideas i'm all ears.

**Comment by mekhami** [comment]
So I did some preliminary research and I think we need to discuss whether we want to do Threading in this project. I think the feature itself isn't worth adding the complexity and fragility of threading, yet, I can't think of another way to accomplish this. I even went so far as to try to add the flag to the PRAW api on every response, or to see if I could accomplish something similar with the Reddit API. Unfortunately every solution points back to threading.

**Comment by michael-lazar** [comment]
I agree, I don't think it's worth making any drastic changes for this ATM. I'm trying to think of other features in the future that would benefit from threading and I can't come up with many. If you can come up with something simple, great! Otherwise don't put too much effort into it. There's a decent sized backlog of feature requests as it is that I think will provide more bang for the buck.

The only solution that I can think of is to add a new key command that checks for unread messages, and shows a little popup notification (similar to how the loading screen looks). It wouldn't give live updates, but it might be useful if you just want to check for new replies without opening your browser.

**Comment by mekhami** [comment]
One thought i had is, is it possible to make one of those little
notification/popups in curses without blocking the UI? perhaps we can do a
post-load query to get_unread() and, while the user is still capable of
interacting with the pages and stuff, a small notification can appear in a
corner or something, maybe on the top status bar. But if the drawing of the
notification is ultimately blocking that will be a problem.

**Comment by michael-lazar** [comment]
Well curses does support windowing off areas of the screen. This is what we're doing right now:

```python
self._header_window = self.stdscr.derwin(1, n_cols, 0, 0)
self._content_window = self.stdscr.derwin(n_rows - 1, n_cols, 1, 0)
```

where the header window is the status bar at the top. You can try manipulating/refreshing the header window separately. Just beware that there's no way to "lock" the window while you're updating it. For example we could be attempting to update the header URL text at the same time that you're updating the notification. In that case bad things will happen. Maybe if you sectioned off a third window...

```python
self._header_window = self.stdscr.derwin(1, n_cols-1, 0, 0)
self._notification_window = self.stdscr.derwin(1, 1, n_cols-1, 0)
self._content_window = self.stdscr.derwin(n_rows - 1, n_cols, 1, 0)
```

**Comment by mekhami** [comment]
So I'm considering what the UI could be for opening up the inbox. /inbox won't work because /r/inbox is an actual subreddit. I thought about /me/inbox which opens up a number of possibilities but I'm not sure if that's functional..

Other than that, perhaps another keystroke, but i'm so hesitant to add more. perhaps this is where using 'i' to check for inbox messages was an oversight.

**Comment by michael-lazar** [comment]
It's a little funky right now. We're currently using the following mappings:

`/r/front` -> `http://www.reddit.com/`
`/r/me` -> `http://www.reddit.com/user/civilization_phaze_3`

BTW `/r/front` is also an actual subreddit, so that ship has sailed.

I'm not especially happy with these (using an alias is quick, but less intuitive) but I couldn't come up with a better solution. I'm open to suggestions. I don't like using the `i` key to open the inbox because it adds another layer to navigation. It's better to keep everything in a centralized place. Especially because the interface for the inbox already looks so similar to `/r/me`. So I would say go with that approach.

`/r/inbox` -> `http://www.reddit.com/message/inbox/`

**Comment by squarehimself** [comment]
I love this app, and I thank you, but the lack of this functionality is the only thing keeping me from using it. I pray this can be added soon!

Also, I agree with the `/r/inbox` approach. It would be the most consistent overall.

**Comment by v1kn** [comment]
I second what @squarehimself said.  
reading/responding to messages it basically the only major thing missing. When it is implemented, `rtv` will be quite perfect.

**Comment by llvtt** [comment]
Is anyone working on this? If not, I'd like to take a stab at it.

As far as how to navigate the inbox goes, I'm in favor of replacing the `i` key with navigation to the inbox. Navigating to the inbox (and seeing clear information about whether or not there are new messages) is more useful than just a message about there being new messages or not.

The downside to this is that it's less consistent with the rest of the UI, which uses "subreddit aliases" like r/me and r/front to have special meaning. IMO, these should be replaced with keyboard commands as well, though that's out of the scope of this particular issue.

**Comment by michael-lazar** [comment]
Afaik no one is working on this, so I would say go for it! 

I agree that it makes sense to use ``i`` for this since it's already bound to the inbox. I don't think anyone will miss it in its current form.

**Comment by jmcblane** [comment]
I hope this gets finished soon!

**Comment by armandg** [comment]
@llvtt any progress on this issue?

**Comment by llvtt** [comment]
@armandg I had made some progress, but it's been so long since I've worked on it or pulled down the latest changes, that I think it's time I pass the baton on this one.

**Comment by squarehimself** [comment]
Is anyone working on this issue?

**Comment by michael-lazar** [comment]
@squarehimself not that I'm aware of

**Comment by jmcblane** [comment]
I would really like to see this feature added. :/

**Comment by ernobe** [comment]
Another feature that could do something similar is to list all the comments of a subreddit (or multireddit), that way you could at least tell if there are new comments in threads you're participating in.  Would that be easier to implement?

**Comment by remembertoremind** [comment]
+1

**Comment by jmcblane** [comment]
So, I've got this hacky method that I use to read my reddit messages from the command line. It utilizes PRAW. Not sure how to merge this into RTV, but here's how I do it:

First, I have an auth script called `redditauth.py` which has the following:
```
#!/usr/bin/env python
import praw

reddit = praw.Reddit(client_id='YourClientID',
                     client_secret='YourClientSecret',
                     user_agent='grabmessages-script',
                     username="YourUsername",
                     password="YourPassword")
```

Then, I have my main script, **redditmessages.py** which generates an output made for **pandoc** to work with:

```
#!/usr/bin/env python
from redditauth import *
import textwrap

inbox = reddit.inbox.unread()
item_list = []

for item in inbox:
    item_list.append(item) 

if len ( item_list ) != 0:
    for item in item_list:
        item.mark_read()
        print("**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**\n")
        print ('**Thread:** ' +  str( item.submission.title + "\n" ) )
        print ('**Author:** ' + str( item.author ) )
        print()
        print ( str( item.body ) )
        print ()
else:
    old_messages = reddit.inbox.all(limit=5)
    print("**No new messages!** Displaying five most recent items:\n")
    for item in old_messages:
        print("**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**\n")
        print ('**Thread:** ' + str( item.submission.title + "\n") )
        print ('**Author:** ' + str( item.author ) )
        print()
        print ( str( item.body ) )
        print ()
```

And finally, my shell script, which passes this to **pandoc**, after which it is passed to **man** for viewing:

```
#!/bin/sh

/PATH/TO/redditmessages.py | pandoc -s -f markdown -t man - | man -l -
```

It does mark messages as read when it brings them in. Thus, currently, if I have new messages in rtv, I just switch over to another terminal and run this to scroll through my messages, at which point I can go back to rtv and find the relevant thread if I want to respond.

Maybe you guys can glean some insight through this? Reading through the documentation of praw, this wasn't too hard to figure out. I'm not familiar with the rtv code, nor am I an experienced coder *(as is probably evident!)*, so it's difficult for me to implement this into rtv myself.

**Comment by jmcblane** [comment]
Sorry for bombarding with so many responses!

I got it to work! Well... sort of. Submitting this here to help kick off this work. Right now, in RTV, with these small changes, I can simply pass `/inbox` and it will display my messages normally as RTV should! If we can make a special case not to check for these certain elements with inbox items, we're good to go!

[mychanges.patch](https://github.com/michael-lazar/rtv/files/2834827/mychanges.txt)

**Comment by jmcblane** [comment]
For anyone looking for a quick solution, I've written this ruby script as an exercise in learning ruby, and it walks through your unread messages, or the last five messages, and gives you the opportunity to reply to those messages. See the attached gif for an example.

Requirements:
`gem install truncate`
`gem install redd`

Also, uses `sed` and `tput` which *should* be on your machine.

https://gist.github.com/jmcblane/e18c4b863a571fece2456aee7101ab06

![take2](https://user-images.githubusercontent.com/25023928/53147552-db684400-3575-11e9-9982-fb3b8777b5f5.gif)

**Comment by michael-lazar** [comment]
Feature branch has been merged! Big thanks to everyone who was patiently watching this issue and provided suggestions and/or examples. Please open new issues if you encounter bugs or limitations with the new implementation, clone the master branch and press <kbd>i</kbd> to check it out.

**Comment by KaKi87** [comment]
Hey, the app says `No New Messages` when I press `i` but I do have messages... :/
