### ISSUE TITLE
threads not lining up correctly

### ISSUE THREAD

**Issue by CaptSpify** [michael-lazar/rtv#117]
Sometimes when I expand a thread, it shows up unaligned:
[Here's how it looks on a webpage](http://i.imgur.com/OFmS5dc.png)
[And here's how it looks in rtv](http://i.imgur.com/iVqQE0G.png)

[Here's a link to the thread, in case it's relevant at all](https://www.reddit.com/r/funny/comments/3cjsth/just_went_to_ikea_for_the_first_time_ever_with_my/cswai3z)

**Comment by michael-lazar** [comment]
Thanks for the detailed bug report.

Also I noticed from your screenshot that your terminal is printing "~@" instead of "•". Does your terminal not support unicode? If so, you might want to try using the ``--ascii`` flag at startup.

**Comment by CaptSpify** [comment]
Thanks for the tip. I did start it with the --ascii flag, and have the same issue:
[Browser](http://i.imgur.com/KZNpe8L.png)
[Terminal](http://i.imgur.com/qNZULqC.png)

**Comment by michael-lazar** [comment]
No I don't think it will fix the issue ;) 

There's a big chunk of logic in the codebase that flattens the comment tree and attaches child comments to their correct spots. It's somewhat convoluted in order to overcome deficiencies in the praw library, my guess is that there's some edge case in there that's not being handled.

**Comment by michael-lazar** [comment]
I finally got around to checking into this. I think the issue was that PRAW wasn't nesting the replies properly when loading more comments. Added a fix here dc56d2524e3aabd6a0a4d5fbd8f9761a146501f8.

![image](https://cloud.githubusercontent.com/assets/5026795/11620317/79f8b55c-9c66-11e5-8690-8b1ac7a781f6.png)
