### ISSUE TITLE
A few more VIM-like keyboard shortcuts for moving pages

### ISSUE THREAD

**Issue by dominicglenn** [michael-lazar/rtv#120]
It would be really useful if the following vim keyboard shortcuts were implemented:

gg - top of document
G - bottom of document
Ctrl-U - up a page
Ctrl-D - down a page

**Comment by michael-lazar** [comment]
Hi, thanks for the input! Here are my thoughts -

You can already jump to the top of a document by refreshing the document (`r`). Jumping to the bottom of the page would only be useful for individual submissions, because the subreddit view is generated on-demand and doesn't have a bottom. Even then I don't really see the utility, it would be like jumping to the last page of google search results. Maybe I'm missing something, can you give me an example of a situation where you would want to do this?

The pgup/pgdn bindings are a good idea and are probably better than what we have currently. However, since there are already two bindings implemented ``m``/``n`` & ``PgUp``/``PgDn``, I'm hesitant to add a third. I think the best thing to do is to is work towards custom key binds https://github.com/michael-lazar/rtv/issues/64.

**Comment by dominicglenn** [comment]
Ah, for some reason I didn't see those page bindings for going up and down in the help screen. My bad. I was just expecting that they would've been mapped to the vim-like bindings.

As for scrolling to the top of the page r means refreshing the page and fetching new data, where as this would be just go to the top of the document that I have right now?

**Comment by mnlgn** [comment]
cmus user here. This was the first thought come in my mind. I would really love to see these shortcuts in rtv as it already feels so natural using them. Usually, I browse the list first up and down based on my time then skip back to top and choose the ones i wanna open/read to. At least the `g` thang. :dog:

**Comment by michael-lazar** [comment]
I just added bindings for ``gg`` and ``G``, sorry it took so long!

 ``Ctrl-U`` and ``Ctrl-D`` were already added in a previous commit.
