### ISSUE TITLE
Typing '/' as subreddit name breaks the application

### ISSUE THREAD

**Issue by tobywhughes** [michael-lazar/rtv#17]
This is the error that I get:     

     Traceback (most recent call last):
     File "main.py", line 102, in <module>
     main()
     File "main.py", line 83, in main
     page.loop()
     File "/usr/lib/python3.4/site-packages/rtv-1.0a2-py3.4.egg/rtv/subreddit.py", line 43, in loop
     self.prompt_subreddit()
     File "/usr/lib/python3.4/site-packages/rtv-1.0a2-py3.4.egg/rtv/subreddit.py", line 89, in prompt_subreddit
     self.refresh_content(name=out)
     File "/usr/lib/python3.4/site-packages/rtv-1.0a2-py3.4.egg/rtv/subreddit.py", line 67, in refresh_content
     self.reddit, name, self.loader)
     File "/usr/lib/python3.4/site-packages/rtv-1.0a2-py3.4.egg/rtv/content.py", line 332, in from_name
     sub = reddit.get_subreddit(name, fetch=True)
     File "/usr/lib/python3.4/site-packages/praw-2.1.20-py3.4.eg /praw/__init__.py", line 1017, in get_subreddit
     return objects.Subreddit(self, subreddit_name, *args, **kwargs)
     File "/usr/lib/python3.4/site-packages/praw-2.1.20-py3.4.egg/praw/objects.py", line 1346, in __init__
     subreddit_name = json_dict['url'].split('/')[2]
     TypeError: 'NoneType' object is not subscriptable
     sys:1: ResourceWarning: unclosed <socket object at 0x7f253b2b5d68>
     /usr/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty

**Comment by tobywhughes** [comment]
I think I figured it out. Just with the way content.py checks /. Going to submit a pull request.

**Comment by michael-lazar** [comment]
Thanks. I'll leave this open since I would rather get everything squared away with a single pull request.
I have some thoughts on switching subreddits in general...

It would be nice to support for all of the following formats:
* /r/python
* /r/python/new
* /r/python/rising
* /r/python/controverisal
* /r/python/top

with optional backslash at the end
* /r/python/
* /r/python/new/
* ...

Using the same convention, we can link back to the front page. I have torn feelings about this one because /r/front already exists as a valid subreddit and using it as an alias feels kinda dirty.
* /r/front
* /r/front/new
* /r/front/rising
* ...

Support for multireddits also fits in nicely
* /r/python+linux
* /r/python+linux/new
* ...

And of course we need to be able bad input without crashing
* /r//
* /r/this/is/fake/
* /r/python/banana

I think at this point it would be best to just refactor the whole from_name() function. I see two options moving forward.
1. Stick to pure python using functions like split('/') and endswith('/new') an be careful around edge cases
2. *shudder* Regular Expressions

**Comment by tobywhughes** [comment]
I don't think were going to have to use regex. I can see it by working in this way
1)Function to check for invalid backslashes
  In this function it can:
  1)Check for backslash at beginning. If there is, raise error
  2)Check for backslash at end. If there is, remove it.
  3)Now, after step two, there should only be one backslash if it is a valid input.
    Here, we check if there is only one backslash. If not, raise error.

2)name, display_type = name.split('/')
3)Check display_type to see if they are valid. If not, raise error.
4)Deal with multireddits. Not sure what we are doing with it so I'll leave that out, but here seems like a logical place to fit it.
5)Check if subreddits are valid.
6)Get subreddits, with a different return depending on display_type.

I'm not sure about the front alias. I guess it could work, sort of like we already have it, but right before step 4, or 5 there can be a check if name = 'front' and have seperate return statements depending on what display_type equal like this:

        if name == 'front':
            if display_type == 'new':
                return cls('New', reddit.get_new(limit=None), loader)
            if display_type == 'top':
                return ...

**Comment by michael-lazar** [comment]
I think this sounds like a good approach.
&nbsp;
The display type should be optional, so we don't want to raise an error if there is no backslash. Something like this should work for step 2.
```python
split_name = name.split('/')
if len(split_name) == 1:
    sub_name, display_type = split_name[0], 'hot'
elif len(split_name) == 2:
    sub_name, display_type = split_name
else:
    raise error
```

**Comment by tobywhughes** [comment]
I instead just had display_type default to 'hot' so that it works like how reddit does it automatically. Just finished reworking it. About to submit it. Didn't deal with multireddits, but I still feel it should be merged since that is a slightly seperate issue than dealing with backslahes.

**Comment by michael-lazar** [comment]
Marking this as closed. We may want to revisit once multireddits are implemented.
