### ISSUE TITLE
Is there a way to set custom colours?

### ISSUE THREAD

**Issue by krompus** [michael-lazar/rtv#181]
I can't find any documentation about this. I suppose I could simply launch in separate terminal with a different colourscheme (indeed, I think that's what I'll do for now), but it would be nice if there was a way to switch around which elements get which term colour.

**Comment by michael-lazar** [comment]
There was some work a while ago to implement this https://github.com/michael-lazar/rtv/pull/97, but it has since been abandoned. Certainly having support for custom themes would be a good thing to have. 

For now, I agree that changing your terminal's colorscheme is the easiest way to do it. RTV only uses the first 8 colors (black, white, red, green, blue, cyan, blue, magenta).

**Comment by krompus** [comment]
Ah, alright, thanks!

For the moment, I'm trying it out with my `cool-retro-term` theme, and it's [pretty nifty (bottom right)](https://i.imgur.com/Bk5ppJE.png). :)

**Comment by michael-lazar** [comment]
Nice!
