### ISSUE TITLE
Posting failed, whole post gone

### ISSUE THREAD

**Issue by supermarin** [michael-lazar/rtv#227]
So I just spent 30 min writing a TIFU post.
Then I quit vim and rtv said it was posting.... 

It failed with something like "captcha missing".

The problem here is, my post is gone, but it's not in any kind of Drafts.
I searched /private/var  for anything with `.txt` extension or `rtv` in it's name,
no luck. So if posting fails, (or even if it doesn't), it'd be ideal if the file was still kept locally.

**Comment by michael-lazar** [comment]
Oh no! I'm sorry that that happened :( 

You're correct that the file is gone, rtv uses temporary files like ``/tmp/rtv-3dGf3fa.txt`` that are deleted when vim closes. I agree that if the post fails it would be good practice to at least prompt the user and give them the option to save the file.

**Comment by kriskropd** [comment]
I've had this happen two or three times to myself too. It's very frustrating. "Woops - all your words are gone and it's not your fault" is a pretty lousy message to read in this day and age.

Why not delete the tmp file after the post has been successfully posted? Like how mutt doesn't remove /tmp message files until after they have been mailed.

Additionally, or instead of - when rtv knows the post failed, why not just ask the user if they would like to try again or save the post to their home directory for later?

**Comment by michael-lazar** [comment]
Hey, I just pushed a patch that keeps the file in */tmp* until after rtv has successfully posted the message. If rtv fails to post, a message will pop-up with the filepath so you can go and grab it. I tried to keep it as simple as possible for now. Hopefully this fixes the issue!

**Comment by supermarin** [comment]
Thanks @michael-lazar!
Agreed with @kriskropd  - you shouldn't be deleting tmp/ files yourself, the filesystem will take care of it.
