### ISSUE TITLE
Installation error w/ python 3

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#245]
```
Installing collected packages: rtv, praw, futures
  Found existing installation: rtv 1.9.1
    Uninstalling rtv:
      Successfully uninstalled rtv
  Found existing installation: praw 3.4.0
    Uninstalling praw:
      Successfully uninstalled praw
  Running setup.py install for futures
    /tmp/pip_build_root/futures/setup.py:6: UserWarning: This backport is meant only for Python 2.
    Python 3 users do not need it, as the concurrent.futures package is available in the standard library.
      warn('This backport is meant only for Python 2.\n'
      File "/usr/local/lib/python3.4/dist-packages/concurrent/futures/_base.py", line 357
        raise type(self._exception), self._exception, self._traceback
                                   ^
    SyntaxError: invalid syntax
    
    
Successfully installed rtv praw futures
Cleaning up...
```

**Comment by tdsmith** [comment]
@ilovezfs and I were troubleshooting a related failure in Homebrew; we think this is because you're building a universal wheel even though Python 2 and Python 3 installs of rtv have different dependencies. I think you should publish separate Python 2 and Python 3 wheels and remove `universal=1` from setup.cfg. If I'm right, this failure won't occur if you install rtv on Python 3 when passing `--no-binary :all:` to pip.

**Comment by michael-lazar** [comment]
Thanks for the tip, I'll look into it

**Comment by michael-lazar** [comment]
I discovered that the boto3 package does the same thing with the futures package and a universal wheel. 

The only difference is that they also define the requirements in [setup.cfg](https://github.com/boto/boto3/blob/develop/setup.cfg) in the **[metadata]** section. I couldn't find any documentation on this so I straight up copied their format. I tested everything locally and it seems to work now; wheels built in py2 install on py3 and vice versa.
