### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by daftz** [michael-lazar/rtv#261]
Hi, when I press 'u' in RTV to login,  it says 'redirecting to reddit' but nothing happens. This is on a raspberry pi (raspbian). RTV is installed with pip3.

On OSX it's working fine.

Any tips? Thanks!

**Comment by michael-lazar** [comment]
Hey daftz, I'm sorry it's not working for you.

How are you connecting to your raspberry pi? If it's over ssh, make sure that the display is getting forwarded e.g. ``ssh -X ...``. Otherwise, you can try setting the ``$BROWSER`` environment variable to a web browser that you know that you know is installed on your pi, e.g. ``export BROWSER=firefox``

**Comment by daftz** [comment]
Hi Michael, thanks! I installed the w3m browser and was able to login. This pi is mainly being used for Domoticz so that's why I did not have any browsers installed :)
