### ISSUE TITLE
[Suggestion] Make Link Posts followable (open in browser)

### ISSUE THREAD

**Issue by mekhami** [michael-lazar/rtv#3]
If the post is not a self post (text post), allow the link the submission leads to to be followable, opening in the default browser.

(Sorry if you don't want suggestions here.)

**Comment by michael-lazar** [comment]
Suggestions are fine! On most terminals that I've tested (at least in Ubuntu and Debian), when you hover over a link with your mouse and right click, an option appears to open the link in your browser. This is what I've been using since it's already built-in and pretty intuitive. If you want to add a keybinding to do this, I would be open to a pull request.

**Comment by mekhami** [comment]
Ah yes I didn't know you could right-click it like that. That's great, I will consider adding a keybinding soon, though. Thanks :+1:
