### ISSUE TITLE
[feature request] (top,controversial) sort by (hour,day,week,month,year,all)

### ISSUE THREAD

**Issue by ReshefElisha** [michael-lazar/rtv#308]
Would be nice to have the ability to go to sort all and controversial. Proposed mapping:

(only in `controversial` or `top` modes):
6 : hour
7 : day
8 : week
9 : month
0 : year
\- : all

**Comment by ReshefElisha** [comment]
In the spirit of hacktoberfest I'll attempt an implementation.

**Comment by michael-lazar** [comment]
Here's a related issue https://github.com/michael-lazar/rtv/issues/244 and PR https://github.com/michael-lazar/rtv/pull/226

**Comment by ReshefElisha** [comment]
Thanks, I'll take a look.
Do you prefer the added menu style or extending the existing menu by adding more options?

**Comment by michael-lazar** [comment]
I think that either of the options that I outlined in #266 would be good. I lean towards adding the additional sub-menu but that I can see that being more difficult to implement. I'm also open to other suggestions if you have any good ideas.

I don't think that we should just extend the menu bar horizontally like this 
```
[1]hot [2]top [3]rising [4]new [5]controversial [6]hour [7]day [8]week [9]month [0]year [-]all
```
because it becomes too cramped.

**Comment by michael-lazar** [comment]
The sub-menu feature has been merged in and is accessible by double-pressing "2" or "5".
