### ISSUE TITLE
Fails to comment when editor is 'emacsclient -nw'

### ISSUE THREAD

**Issue by kozross** [michael-lazar/rtv#317]
When I try to use the 'c' command to post a comment, I get the message 'Could not open file with emacsclient -nw'. This works elsewhere (such as mutt) normally.

**Comment by michael-lazar** [comment]
Thanks, this is probably failing because the python subprocess call doesn't allow flags in the first argument.

https://github.com/michael-lazar/rtv/blob/master/rtv/terminal.py#L555
```python
p = subprocess.Popen([editor, filepath])
```
It should be pretty easy to fix using something like [shlex.split](https://docs.python.org/2/library/shlex.html#shlex.split).

**Comment by michael-lazar** [comment]
I was able to replicate your error and I just pushed a fix to the master branch. Hopefully this should resolve your issue!
