### ISSUE TITLE
On windows cygwin using firefox as browser causes the Timeout opening browser message to appear

### ISSUE THREAD

**Issue by raviu** [michael-lazar/rtv#341]
This happens even though the browser is open and running. The timeout reaches and this message is displayed. If we close firefox prior to the timeout a proper returncode is sent back and we don't see that message. 

But I find that reading something on the browser and going back to rtv, the experience is kind of broken by this message and having to key in something to get rid of it before I continue browsing. 

I have got rid of this message locally after trying to fix it but I think it's expected behaviour not to get a returncode until the process is terminated. [1]

Do we really need this message to be displayed? How about putting it on a timer or only having this information in the logs? 

[1] https://github.com/michael-lazar/rtv/blob/88d8001bf12659e88b7a36eb35272c5e73934d49/rtv/terminal.py#L499-L501

**Comment by michael-lazar** [comment]
I'm clearing out old issues, and closing this because Windows is not a target platform (even on cygwin). From what I've observed on Linux / OS X, the webbrowser code does return an exit code of 0 after opening a new tab. The python webbrowser module is very OS-specific so I don't doubt that it might be different on Windows. My apologies for not responding to this earlier.
