### ISSUE TITLE
Please add hotkey for copy url

### ISSUE THREAD

**Issue by averrin** [michael-lazar/rtv#346]
I was very surprised when `y` didnt copy url... =(

**Comment by michael-lazar** [comment]
You mean copy it to the clipboard? Can you explain your use case further?

**Comment by averrin** [comment]
Yes, to clipboard. Use case is simple - I want to share it. And before send it by messenger I need copy url.

**Comment by noahfx** [comment]
Hi, 
I have implemented a solution for this https://github.com/noahfx/rtv/commit/7a2d248875918a69a1fb5bd1e39a4fae4bdc5ebf
@michael-lazar the reason why I have not made a PR yet is because it seems the library (pyperclip) fails sharing the clipboard outside the python application if there isn't some kind of clipboard manager installed, I think it is related with this https://github.com/asweigart/pyperclip/issues/61.

Do you have any suggestion? Any other library?

**Comment by shaggytwodope** [comment]
A few thoughts towards @noahfx's solution. Assuming it's not changed, this would introduce some optional depends for packaging. And I personally think while this functionality is certainly welcomed. It would be ideal to be disabled by default. With packaging for AUR this is no problem. However many people install via PIP.

**Comment by michael-lazar** [comment]
Thanks for working on this issue! I'm fine with adding a section in the README that says you need to install ``xclip`` or ``xsel`` separately to get it to work on linux. It would be similar to what ended up happening with ``urlview``. We would need to add a descriptive error message if you press the key but the appropriate program isn't installed.

That being said, it looks like outside of supporting the Windows clipboard, all that pyperclip is doing is piping commands to subprocesses. Do you think it would be better to avoid adding another python dependency and just call the commands directly?

**Comment by noahfx** [comment]
Hi, 
I removed the pyperclip dependency and implemented my own copy :) 
Here is the PR of the feature https://github.com/michael-lazar/rtv/pull/364

**Comment by michael-lazar** [comment]
Merged in #364

**Comment by rigopoui** [comment]
This issue persists for wayland. My guess is that internally the program uses xclip, and not wl-copy
