### ISSUE TITLE
Searching reddit would be nice

### ISSUE THREAD

**Issue by dominicglenn** [michael-lazar/rtv#39]
Searching reddit would be nice

**Comment by michael-lazar** [comment]
Can you give an example use-case of how you would use the search?

Implementing this would be pretty straightforward using praw's [search](http://praw.readthedocs.org/en/latest/pages/code_overview.html#praw.__init__.UnauthenticatedReddit.search) function. Maybe instead of using ``/`` to open the subreddit prompt, you could use ``f`` (find) to open a search prompt. I don't know about any of the advanced filtering.

**Comment by Brobin** [comment]
I implemented a basic search for searching a sub. You can check it out [here](https://github.com/Brobin/rtv/tree/search_subreddit)

[diff 1](https://github.com/Brobin/rtv/commit/26aab7a2cd65022e5eefdfd95abd54606de7ddc1)
[diff 2](https://github.com/Brobin/rtv/commit/f9265fd33b3bbe074890cd8fb7679cc45f2c4836)

**Comment by Brobin** [comment]
Opened a pull #56

**Comment by michael-lazar** [comment]
Yea make a pull request please. A couple of things I noticed:

- Will need a special case for the front page
- Might want to make the prompt a different color to differentiate from the subreddit prompt. green or yellow maybe?
- Should be catching specific exceptions in your **try-except** block
- Are multireddits searchable? E.g. ``/r/python+programming``
