### ISSUE TITLE
[feature request] sort subreddit search by new, relevance, top, comments

### ISSUE THREAD

**Issue by sodiumjoe** [michael-lazar/rtv#393]
You can do this in the web ui. Currently, if you do a subreddit search (`f`), then sort by "new" for example, (`4`), rtv returns to the subreddit's new page.

**Comment by michael-lazar** [comment]
Agreed, this would be nice to have.

**Comment by michael-lazar** [comment]
The sorting options will now be applied to the current search, instead of discarding the query and refreshing the page.

Currently you can sort by (``hot``, ``new``, ``top``, ``rising``, ``controversial``). I opened a new issue to change the options to (``new``, ``relevance``, ``top``, ``comments``) for search results. https://github.com/michael-lazar/rtv/issues/401
