### ISSUE TITLE
Application crashes after typing "i" after some idle time

### ISSUE THREAD

**Issue by HrushikeshK** [michael-lazar/rtv#469]
I'm running rtv on Arch Linux 4.13.8-1-ARCH.
**rtv** crashes when I try to view new messages using "i" after it is being idle for around 5 mins.
[This](https://pastebin.com/qr86vFfD) is the stack trace after the error occurs. It is probably because of timeout exception.

**Comment by michael-lazar** [comment]
Thanks for the bug report

**Comment by HrushikeshK** [comment]
Also, I'm not able to view new messages after pressing "i", it just shows "New Messages".
How do I view those messages?

**Comment by michael-lazar** [comment]
Implementing that functionality is an open issue, see https://github.com/michael-lazar/rtv/issues/109

**Comment by michael-lazar** [comment]
There seem to be a lot of people experiencing this error with reddit and praw:

https://www.reddit.com/r/redditdev/comments/4hjtfg/praw_read_timed_out_error/
https://www.reddit.com/r/redditdev/comments/5jdu64/api_connection_stops_after_one_hour
https://www.reddit.com/r/redditdev/comments/3qroun/problem_keeping_praw_with_oauth2_running/

**Comment by michael-lazar** [comment]
I improved the error handling so you should now see an "HTTP request timed out" message instead of a a fatal stack trace. I still don't know what's causing the underlying timeout to occur. Either the reddit api is choking and sending invalid HTTP data, or your ISP is spotty or doing something weird. In either case, it doesn't seem like something that RTV has control over.
