### ISSUE TITLE
Use surf as $RTV_BROWSER

### ISSUE THREAD

**Issue by farmerdjay** [michael-lazar/rtv#471]
I use surf as the $RTV_BROWSER, but the "Timeout waiting for browser to open" error will show up not long after the browser opened. You explained the situation in [#433](https://github.com/michael-lazar/rtv/issues/433) very clearly, it makes me wonder if my problem will be solved if 'surf' is added to the [console_browsers](https://github.com/michael-lazar/rtv/blob/331492c766ac8879cfadf7de72dde2ae62486c42/rtv/terminal.py#L110).

Thank you very much.

**Comment by michael-lazar** [comment]
I haven't used surf before but you're probably right that a special rule will need to be added. It's not a TUI browser so I don't know if adding it the the console_browsers list is the best thing to do. You would still want it to open in the background instead of blocking rtv while the link is open.

**Comment by farmerdjay** [comment]
Out of curiousity, I added the 'surf' to the console_browsers list in the terminal.py. The timeout error no longer shows up, it works perfectly: open the link in surf --> close the window when I am done --> pop right back to rtv.

**Comment by michael-lazar** [comment]
I registered surf as a ``webbrowser.BackgroundBrowser``, so now it should open in a new window by default without the timeout error. I really like surf, I'm going to try to use it more often 😄
