### ISSUE TITLE
Can't use it on emacs-shell

### ISSUE THREAD

**Issue by fuzunspm** [michael-lazar/rtv#483]
i can login and it's working actually but it won't navigate or scroll. It also displays wierd characters, please have a look at the image file below

http://oi66.tinypic.com/333iucp.jpg

Edit:

I'm on 10.13.1 macOS
installation done via homebrew
emacs running on shell with xterm 256 colors

**Comment by michael-lazar** [comment]
Possible related issue: https://github.com/michael-lazar/rtv/issues/459

**Comment by fuzunspm** [comment]
i already up to date via homebrew and this issue seems different than #459

**Comment by michael-lazar** [comment]
My best guess is that your ``$TERM`` environment variable inside of emacs shell is incorrectly set to something like ``TERM=xterm-color256`` instead of ``TERM=dumb`` ([link](https://emacs.stackexchange.com/questions/10137/what-does-term-dumb-in-eshell-mean)). The emacs shell only supports a subset of xterm commands, so you end up with the escape sequences like ``^[(B`` getting dumped to the screen instead of interpreted as actions like "move the cursor right 3 characters".

I would suggest using ``M-x term`` instead of shell, and running ``$ env TERm=eterm-color rtv``.
