### ISSUE TITLE
Attempting to access private subreddit crashes on launch

### ISSUE THREAD

**Issue by selvodka** [michael-lazar/rtv#496]
When launching rtv it outputs in a rectangle   "not found" but when downgrading to rtv-1.20.0-1 works normally 
Running 
Kernel : 4.9.71-1-MANJARO 
DE: Xfce

**Comment by michael-lazar** [comment]
how did you install it?

**Comment by selvodka** [comment]
pacaur -S rtv

**Comment by michael-lazar** [comment]
Unfortunately I am not able to reproduce this on my laptop running Arch. The only thing that I can think of is that it might be related to the latest release moving the authentication token from

```
$XDG_CONFIG_HOME/rtv/refresh-token (~/.config/rtv/refresh-token)
```

to

```
$XDG_DATA_HOME/rtv/refresh-token (~/.local/share/rtv/refresh-token)
```

Maybe the permissions on the ``$XDG_DATA_HOME`` directory are set in a way that rtv can't access it? You can try launching with the ``rtv --log rtv.log`` flag and pasting the log file here, it might reveal something.

**Comment by selvodka** [comment]
https://pastebin.com/raw/H8X869BC

**Comment by michael-lazar** [comment]
Sorry for the late response, copy ``~/.config/rtv/refresh-token`` to ``~/.local/share/rtv/refresh-token``. 

It looks like when you first launch rtv, you're trying to access a private subreddit (``/me/m/asia/new``), which isn't working because you need to re-authenticate your credentials.

This is an edge case that should be handled by rtv without crashing, so I'm going to keep this issue open and promote it to a bug.
