### ISSUE TITLE
XDG standard instead of mailcap

### ISSUE THREAD

**Issue by aleprovencio** [michael-lazar/rtv#509]
Hello!
According to the arch wiki [1], the XDG standard is the most common for configuring desktop environments, so I try to use it everywhere I can on my system. RTV seems to prefer mailcap over it, so I have two questions:

1) Any special reason on why you choose that over XDG?
2) The wiki also says I can put `*/*; xdg-open "%s"` on my mailcap file and it will use the XDG confs but that will not work for RTV, do you know why?

[1] https://wiki.archlinux.org/index.php/Default_applications

**Comment by michael-lazar** [comment]
I went with mailcap because it was suggested by someone and it appeared to be the solution that other, similar TUI applications are using. I've used xdg-open before on Ubuntu but I didn't register that it was a standard across distributions. It looks like it's tied to the desktop environment so it's not clear to me that it would work for headless setups. Like could I set your web browser to ``lynx`` and have it open in the same window as rtv, or would it open in a new terminal window? Also it doesn't look like it will work on macOS which is a large swath of users. 

> The wiki also says I can put */*; xdg-open "%s" on my mailcap file and it will use the XDG confs but that will not work for RTV, do you know why?

See the disputed footnote: https://wiki.archlinux.org/index.php/Talk:Default_applications#Wildcards_in_mailcap

The discussion is correct, the python mailcap library also does not accept ``*/*`` entries. You need separate entries for

```
*/video
*/image
*/text
```
etc.

**Comment by aleprovencio** [comment]
Thanks for the info @michael-lazar, I didn't notice the disputed footnote and now I can successfully make mailcap hand over tasks to xdg-open.

I think xdg-open works well on DE-less setups such as mine, but after investigating further it doesn't seem much better then mailcap, and as you said, it is less popular. 

Mailcap seems like my choice for now.
