### ISSUE TITLE
RSS reader / wikipedia browser

### ISSUE THREAD

**Issue by tobimensch** [michael-lazar/rtv#510]
Hello,

rtv is among the best command line applications I've ever seen.

I haven't found any rss feed readers or wikipedia browsers on the same
level of usability as rtv for the command line.

Could you integrate those features into rtv?

**Comment by michael-lazar** [comment]
Thanks for the kind words!

My opinion is that I would rather focus on improving the existing reddit interface, instead of trying to branch out into other areas. There are enough open issues that there will always be things that improve, and I have limited time to devote to the project these days. Hopefully other developers will be able to take some of the ideas from rtv and use them to build their own terminal applications.
