### ISSUE TITLE
RedditVideoMIMEParser returns 'video/x-youtube' MIME type

### ISSUE THREAD

**Issue by Crestwave** [michael-lazar/rtv#552]

**Comment by michael-lazar** [comment]
What MIME type are you expecting it to return?

**Comment by woorst** [comment]
This issue explains the reasoning: #409

**Comment by michael-lazar** [comment]
To summarize, the decision was made to use the ``video/x-youtube``mimetype because most people map this type to youtube-dl/mpv/vlc, and those applications (at least newer versions) support opening v.redd.it links. This avoids the complexity of needing to define another custom MIME type. I just tested a bunch of v.redd.it links on my laptop and confirmed that mpv still works for me, even without needing @woorst 's updated mailcap configuration. 

If you need more granularity, you could work around this by writing a custom shell script to check if the URL is v.redd.it,  and then redirect to the appropriate program yourself. E.g.

```
video/x-youtube; my_opener.sh '%'; test=test -n '$DISPLAY"
```
