### ISSUE TITLE
Use reverse video instead of line at left.

### ISSUE THREAD

**Issue by pthfdr-42** [michael-lazar/rtv#558]
You should use reverse video instead of a line at left to highlight current entries. Like this:
![(I highlighted an entry using the mouse.)](https://user-images.githubusercontent.com/31236558/40886867-04889f8a-672f-11e8-9704-44b3836f610e.png)

**Comment by michael-lazar** [comment]
I'm not going to change the default theme because in my opinion the bar on the left looks better.

However, this is a great use-case for creating a custom theme. If you take the default [theme template](https://github.com/michael-lazar/rtv/blob/master/rtv/themes/default.cfg.example) and change the ``Selected`` line to:

```
;<element>            = <foreground>  <background>  <attributes>
Selected              = default       default       reverse
```

you should get exactly what you want. See [THEMES.md](https://github.com/michael-lazar/rtv/blob/master/THEMES.md) for info on how to install a custom theme.
