### ISSUE TITLE
Is it possible to refresh the comments after making a comment?

### ISSUE THREAD

**Issue by Hund** [michael-lazar/rtv#562]
Is it possible to refresh the comments after making a comment so I don't have to do it manually every time I make a comment?

**Comment by michael-lazar** [comment]
Yes, in fact the current behavior is to sleep two seconds and then automatically reload the page. The issue is that reddit takes a few moments to add the comment on the backend, so it doesn't always show up right away if you refresh immediately. The two second window used to be enough time, but that might need to be revisited.

https://github.com/michael-lazar/rtv/blob/1275e1249b721f09c9630188a5d46e7b6d17fe99/rtv/submission_page.py#L206-L212

**Comment by Hund** [comment]
I see. :) Thanks!
