### ISSUE TITLE
read password from file or ask at application startup to keep username/password out of `ps` results

### ISSUE THREAD

**Issue by spigot** [michael-lazar/rtv#6]
having to login with -u and -p options leaves my username and password visible for anyone on the machine to see when listing open processes.

**Comment by michael-lazar** [comment]
See https://github.com/michael-lazar/rtv/pull/1

**Comment by michael-lazar** [comment]
I'll leave this open because I think it would be a good idea to have a general config file for things like this.

> kryptic_mind
> It would be great to add some kind of dotconfig file (login, password, default subreddit, so on) in the future. WDYT?

**Comment by shanhind** [comment]
I'm going to do this to start with at least for storing username, password and default subreddit in a config file in the home directory.

**Comment by michael-lazar** [comment]
I was working on this last night. See 8201460e9c6f648520d0937ad30188bf96e54584

RTV will check for the file `~/.rtv`, with the following format
```
[rtv]
username=myusername
password=mypassword
subreddit=mydefaultsubreddit
```

All of the arguments are optional. If specified, they will overwrite the default arguments for the script. I'm open for discussion about naming and best conventions since I don't have much experience in this area.

**Comment by shanhind** [comment]
Looks like this was already completed in 8201460e9c6f648520d0937ad30188bf96e54584.

**Comment by michael-lazar** [comment]
;)
