### ISSUE TITLE
Rebindable Keys

### ISSUE THREAD

**Issue by Ram-Z** [michael-lazar/rtv#64]
Allow rebinding keys in the config file.

**Comment by tobywhughes** [comment]
I'll take a look at this today and see how hard it would be.

**Comment by michael-lazar** [comment]
Here's an example of another Python project that handles this pretty well. https://github.com/bpython/bpython/blob/master/bpython/sample-config#L56

**Comment by rpesche** [comment]
Hello !
I wan't to work on this enhancement.
Is there any work done about it ?

**Comment by michael-lazar** [comment]
Hi rpesche! Thanks for offering to help, there has been no work done on this so far AFAIK.

I'm currently in the middle of refactoring a bunch of large components, including how the config is loaded and stored internally. The branch is here https://github.com/michael-lazar/rtv/blob/future_work/rtv/config.py. Because things will be changing within the next few weeks, I would recommend waiting until the next update before starting to implement anything new on top of the master branch.

**Comment by rpesche** [comment]
Ok, I'm waiting for the merge of your branch !

**Comment by michael-lazar** [comment]
Hey, FYI I just merged everything into master. I'll be doing a lot of testing over the next couple of days, but will only be pushing bugfixes. You're good to go now if you want to start working on this.

**Comment by rpesche** [comment]
Ok ! I'm working on it.
I had made the branch rpesche/rtv to store my work

**Comment by michael-lazar** [comment]
10 months and 3 failed attempts later, it's finally in! #195
