### ISSUE TITLE
RTV exits when user home page has no submissions

### ISSUE THREAD

**Issue by cmtholm** [michael-lazar/rtv#651]
When logging in to an account that follows no subreddits a message is displayed:
│`/r/front` has no submissions│

Following this, any key press exits RTV. Seems a more explanatory message would be beneficial, as well as still giving access to the normal navigation commands for RTV. Or RTV should default to Popular, then allow the user to navigate from there.

As is, a user with no front page submissions must specify rtv -s "subreddit" to use the application

**Comment by michael-lazar** [comment]
RTV is currently unable to render an empty page because it doesn't know what to do with the cursor when there's no element to select. I agree that it's confusing from a UI perspective, and it would be better to have an empty page and allow the user to enter navigation commands. It's just such a small edge case that it's been hard to justify the amount of code necessary to fix it.

**Comment by michael-lazar** [comment]
I went ahead and added the fix that you suggested of defaulting to ``/r/popular`` instead of the user's front page.
