### ISSUE TITLE
[Feature Request] Ability to hide visited links.

### ISSUE THREAD

**Issue by shaggytwodope** [michael-lazar/rtv#99]
Would it be possible hide visited links, perhaps from the history log introduced in #81 by @Brobin ? Not in individual sub reddits tho, just on /all or front. Apologies if this has been mentioned before.

**Comment by michael-lazar** [comment]
Why only on the front page only? I can understand wanting to be able to turn the history on or off all together. Could you explain your reasoning?

**Comment by shaggytwodope** [comment]
Sure thing, what I had in mind was hiding visited links on the front page. This makes for faster viewing of new content. But the posts still remain when visiting individual sub's. Not sure it would make sense to hide them there. If I were to want to surf that sub. Or just hiding visited links in general would work. But maybe toggle them when visiting some subs directly? (To post/read new comments on threads that may have been updated/changed for whatever reason)

**Comment by michael-lazar** [comment]
Hmm I see, thanks for elaborating. It sounds like what you want is a special way to sort posts. So right now you can do `/r/python/new` to sort the page by new posts. We might be able to add a new directive like `/r/python/unseen` that sorts by `new` and filters out previously opened posts. This would be fairly difficult to implement, but definitely doable. Personally, I don't think that I would find it that useful because I find that the purple links are enough of a visual cue. Also it would make it difficult/impossible to view the comments for a post after you have opened the link, no?

**Comment by shaggytwodope** [comment]
Indeed that does make it complicated to view a post after opening the link. I think my idea is a bit flawed lol. But that's why I mentioned only hiding links on front page rather then the subs themselves. But if this is remotely hard to work out then by all means close the issue, sorry to bothered ya.

**Comment by michael-lazar** [comment]
Don't be sorry, it's not a bad idea! I appreciate hearing people's ideas and perspectives about what's good and what could be changed. Even if we don't implement this directly, we may be able to incorperate it in the future or draw inspiration from it. :+1:
